### PR TITLE
Nanoseconds support

### PR DESCRIPTION
**Pull request by SovGVD**

### CODE REVIEW

**Comment by shamil** [comment]
@SovGVD not sure what is the purpose of this, cause AFAIK zabbix trapper protocol supports timestamp (clock) only in seconds. 

I prefer this library to be complaint with official specification. See [here](https://zabbix.org/wiki/Docs/protocols/zabbix_sender/3.0) for more info...

**Comment by SovGVD** [comment]
Possibly the official specification is outdated. My changes based on this [patch](https://github.com/AlekSi/zabbix-sender/pull/4) and also discussions in Zabbix bug tracker:
 - https://support.zabbix.com/browse/ZBX-10234
 - https://support.zabbix.com/browse/ZBX-11883

And some other rare `Nanoseconds` notices.

**Comment by shamil** [comment]
@SovGVD thanks for the info. Seems like they show example of this only in the Agent protocol page (https://www.zabbix.org/wiki/Docs/protocols/zabbix_agent/3.4)

In any case, your PR is a bit incomplete, cause it doesn't take into account the `ns` of the whole payload. Also I prefer the `ns` configuration will be part of the `instance` and not specified in `addItem`.

I've prepared a PR https://github.com/shamil/node-zabbix-sender/pull/3 which add support fro `nanoseconds` but implemented a bit differently. 

Let me know if that fits your needs, and I'll merge it and release a new version to NPM

**Comment by SovGVD** [comment]
In my case I have a lot of items from huge CSV file with different timestamps per items (up to 90k items per hour and up to 48 hours of items in file), the CSV file update ones per 1-2 hours (it's an extra handler for it with inotify). It's a little bit unusual case I think =) So no worries.

**Comment by shamil** [comment]
closing in favor of #3

**Pull request closed without merging**
